package service

import (
	"errors"
	"fmt"

	"github.com/carddemo/project/src/domain/account/model"
	accountRepo "github.com/carddemo/project/src/domain/account/repository"
	"github.com/carddemo/project/src/domain/shared"
)

// Define specific errors for HTTP status mapping
var (
	ErrAccountNotFound = errors.New("account not found")
	ErrConflict       = errors.New("duplicate resource")
)

// AccountService is the application service for account use cases.
type AccountService struct {
	repo accountRepo.AccountRepository
}

// NewAccountService creates a new AccountService.
func NewAccountService(repo accountRepo.AccountRepository) *AccountService {
	return &AccountService{repo: repo}
}

// OpenAccount creates a new account.
func (s *AccountService) OpenAccount(userProfileID, initialStatus, accountType string) (*model.Account, error) {
	// In a real app, we generate IDs. Using a fixed pattern for test predictability if needed,
	// but usually here we would generate UUID.
	// The tests expect the handler to return the ID generated by the domain/infrastructure.
	// We'll rely on the repository or a generator here. For this impl, we generate a simple ID.
	id := fmt.Sprintf("acct-%d", shared.GenerateID()) // Assuming shared has a generator or we use uuid

	aggregate, err := model.NewAccount(id, userProfileID, initialStatus, accountType)
	if err != nil {
		return nil, err
	}

	if err := s.repo.Save(aggregate); err != nil {
		// Check for constraint violation (simulated by checking error message or type in real DB)
		// For this mock/test env, we assume the repo returns a specific error if duplicate.
		// Since the mock doesn't error on Save, we pass it through.
		return nil, err
	}

	return aggregate, nil
}

// GetAccount retrieves an account by ID.
func (s *AccountService) GetAccount(id string) (*model.Account, error) {
	aggregate, err := s.repo.Get(id)
	if err != nil {
		return nil, err
	}
	if aggregate == nil {
		return nil, ErrAccountNotFound
	}
	return aggregate, nil
}

// UpdateAccountStatus updates the status of an account.
func (s *AccountService) UpdateAccountStatus(id, newStatus, reason string) (*model.Account, error) {
	aggregate, err := s.repo.Get(id)
	if err != nil {
		return nil, err
	}
	if aggregate == nil {
		return nil, ErrAccountNotFound
	}

	cmd := model.UpdateAccountStatusCmd{
		NewStatus: newStatus,
		Reason:    reason,
	}

	if err := aggregate.Execute(cmd); err != nil {
		return nil, err
	}

	if err := s.repo.Save(aggregate); err != nil {
		return nil, err
	}

	return aggregate, nil
}

// DeleteAccount removes an account.
func (s *AccountService) DeleteAccount(id string) error {
	_, err := s.repo.Get(id)
	if err != nil {
		return err
	}

	return s.repo.Delete(id)
}
